[project]
site_name = "Aprende VueJS"
site_description = "Aprende VueJS"
nav = [
  {"Introducción" = "index.md"},
  {"Usando Vue" = "usandoVue.md"},
  {"Creando proyecto Vue" = "creandoProyecto.md"},
]

[project.theme]
language = "es"
