[project]
site_name = "Aprende VueJS"
site_description = "Aprende VueJS"
nav = [
  {"Introducción" = "index.md"},
  {"Integrando Vue" = "integrandoVue.md"},
  {"Creando proyecto Vue" = "creandoProyecto.md"},
  {"Analizando estructura de un proyecto Vue" = "analizandoProyectoVue.md"},
  {"Gestionando estados" = "gestionandoEstados.md"},
  {"Props y Emmits" = "propsEmmits.md"},
  {"Router Vue" = "routerVue.md"},
  {"Pinia" = "pinia.md"},
]

[project.theme]
language = "es"
logo = "img/vuejs-logo.png"	

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
