[project]
site_name = "Aprende VueJS"
site_description = "Aprende VueJS"
nav = [
  {"Introducción" = "index.md"},
  {"Usando Vue" = "usandoVue.md"},
  {"Creando proyecto Vue" = "creandoProyecto.md"},
  {"Analizando estructura de un proyecto Vue" = "analizandoProyectoVue.md"},
  {"Gestionando estados" = "gestionandoEstados.md"},
  {"Props y Emmits" = "propsEmmits.md"},
  {"Router Vue" = "routerVue.md"},
  {"Pinia" = "pinia.md"},
]

[project.theme]
language = "es"
